// dummy main theme for dummytest. Same mechanism as the kit's Teal preset:
// one main colour drives BOTH the accent tokens (buttons / links / focus / info)
// AND the top bar + command bar (nav-* tokens). Generated by new-service.mjs.
import { setTokenOverride } from 'lilak-ui'

export const DUMMYTEST = {
  "btn-primary-bg": "#9333ea",
  "btn-primary-hover": "#7d2bc7",
  "btn-primary-text": "#ffffff",
  "text-link": "#9333ea",
  "text-link-hover": "#7d2bc7",
  "border-focus": "#9333ea",
  "input-focus-border": "#9333ea",
  "info-bg": "#f0e2fc",
  "info-text": "#7d2bc7",
  "selection-bg": "rgba(147,51,234,0.28)",
  "nav-bg": "#9333ea",
  "nav-border": "#812dce",
  "nav-accent": "#812dce",
  "nav-text": "#ffffff",
  "nav-text-muted": "#dfc2f9",
}

/** Apply the dummytest colour overrides on top of the active base theme (call after applyTheme()). */
export function applyMainColor() {
  for (const [name, value] of Object.entries(DUMMYTEST)) setTokenOverride(name, value)
}

// Only 'bright' is offered — the main colour is fixed via overrides, so
// dark/lowcontrast barely differ. Add their ids back here to offer them.
export const ENABLED_THEMES = ['bright']
