/**
 * Shell — dummytest chrome: a thin config of the kit's AppShell (top bar, /command
 * bar, \ drawer, ? shortcuts, tab hotkeys). Generated by new-service.mjs; edit
 * TABS / status / labels here, fill the pages under src/pages/.
 */
import { useState } from 'react'
import { AppShell, useLang } from 'lilak-ui'
import { ENABLED_THEMES } from '../theme/main'
import Placeholder from '../pages/Placeholder'


const TABS = [
  { id: "home", icon: "home" },
]

export default function Shell() {
  const { t, lang } = useLang()
  const [tab, setTab] = useState("home")

  const tabs = TABS.map((x) => ({ id: x.id, label: t('tab_' + x.id), icon: x.icon }))

  const status = (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontFamily: 'var(--font-mono)', fontSize: 'var(--fs-tiny, 11px)', color: 'var(--nav-text)' }}>
      <span style={{ width: 6, height: 6, borderRadius: '50%', backgroundColor: 'var(--nav-text-muted)' }} />
      {t('status_idle')}
    </span>
  )

  const labels = {
    help: t('cmd_help'), system: t('nav_system'), theme: t('set_theme'), language: t('set_lang'),
    account: t('nav_account'), notifications: t('notif_title'), command: t('cmd_placeholder'), shortcuts: t('shortcuts_title'),
  }

  const PAGES = {
    home: <Placeholder icon="home" title={t('tab_home')} note={t('placeholder_home')} />,
  }

  return (
    <AppShell
      brand={lang === 'ko' ? t('brand') : 'lilak'}
      service={t('svc_name')}
      tabs={tabs}
      active={tab}
      onTab={setTab}
      themes={ENABLED_THEMES}
      status={status}
      labels={labels}
    >
      {/* Keep every tab mounted (display toggle) so page state survives switches. */}
      {TABS.map(({ id }) => (
        <div key={id} style={{ height: '100%', display: tab === id ? 'block' : 'none' }}>{PAGES[id]}</div>
      ))}
    </AppShell>
  )
}
